#!/usr/bin/env bash

function install_bower {
  bower install skeleton-css
  bower install jQuery
  if [ "$2" == 'angular' ]; then
    bower install angular
    bower install angular-route
  fi
}

function angular_template {
  cd js

  if [ "$2" == 'angular' ]; then
    mkdir controllers routes
    cd routes
    curl https://gist.githubusercontent.com/oelizondo/dc60cbd21d4530f24424/raw/8018340a8906064d71537f4eb85c7638153342c1/routes.coffee -o routes.coffee
    cd ..

    mkdir build

    cd build

    curl https://gist.githubusercontent.com/oelizondo/a19a267a1846cc3739af/raw/def664adfd25318ecfc691a0bf2dcd7e68190623/app.js -o main.js

    cd ..
  else
    curl https://gist.githubusercontent.com/oelizondo/84c3b419ccaa7cd1f0f5/raw/8b1175bebce7f7af7b6e9904846f70a3835482fb/main.coffee -o main.coffee
  fi

  cd ..

}

echo 'Welcome to Sofia!'

if [ -f /usr/local/bin/node ]; then

  mkdir $1

  cd $1

# Installs dependencies

  if [ -f /usr/local/bin/bower ]; then
    echo 'Bower has been included so you can add your personal dependencies. Installing Skeleton and jQuery...'
    install_bower $2
  else
    echo 'Do you want Sofia to install bower?'
    read answertwo
    if [ "$answertwo" == 'y' ]; then
      echo 'Installing bower'
      sudo npm install --g bower
    fi
  fi

# Starts project scaffold
echo "Creating $1..."

  curl https://gist.githubusercontent.com/oelizondo/d8b7bbb34739d40197f0/raw/377f7b88326afcf1fe644fc2767b1495314f2c11/index.html -o index.html

  curl https://gist.githubusercontent.com/oelizondo/f51df1467385f25b6acf/raw/6a1fcc129d8e701f8174083f043b96d5c7fe6935/gulpfile.js -o gulpfile.js

  mkdir assets js css

  cd assets

  mkdir images fonts videos

  cd ..

  cd css

  curl https://gist.githubusercontent.com/oelizondo/3ea02d6ee423fdb24e69/raw/765890f336763c285921756a99cfffe03724166b/style.scss -o style.scss

  touch _variables.scss

  touch _mixins.scss

  cd ..

  angular_template $2

  gulppackages=(
    gulp-live-server
    gulp-sass
    gulp-plumber
    gulp-watch
    gulp-coffee
  )

  echo 'Installing gulp packages...'
  sudo npm install --save-dev gulp

  for package in "${gulppackages[@]}"
  do
    echo 'hould Sofia install: (y/n)' $package
    read install_option
    if [ "$install_option" == 'y' ]; then
      sudo npm install --save-dev $package
    fi
  done


  echo 'Sofia is done! Just run gulp to start working!'

else
  echo 'Node is not normally where it should be, should we install Node.js (y/n)?'
  read yon
  if [ "$yon" == 'y']; then
    cd
    git clone git://github.com/ry/node.git
    cd node
    ./configure
    make
    sudo make install
  fi
  echo 'All set. You can now use Sofia.'
  echo 'Bye <3'
  exit
fi