#!/usr/bin/env bash

### Utility Functions ###
function help {
  echo "% Sofia's Help Module %"
  echo "For creating a new project: sofia new <project_name>"
  echo "For creating a new slim project: sofia slim <project_name>"
  echo "For version: sofia version or sofia v"
  exit
}

function run_boiler_plate {
  echo "Creating $1"
  mkdir $1 && cd $1
  mkdir js css assets
  touch css/styles.css js/index.js
}

function default_html_boilerplate {
  echo "<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset='UTF-8'>
    <title>Title</title>
  </head>
  <body>
    
  </body>
</html>" > index.html  
}

function create_default {
  node=$(which node)
  run_boiler_plate $1
  touch css/style.scss
  if [ ! -z $node ]; then
    npm init -y
  else
    echo "Install node"
    exit
  fi
}

function create_slim {

  run_boiler_plate $1

  echo "Created folders"

  echo "<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset='UTF-8'>
    <title>Title</title>
  </head>
  <body>
    
  </body>
</html>" >> index.html

  echo "$1 ready."
  exit
}

#Sofia's Version
if [ "$1" == "--version" ] || [ "$1" == "-v" ]; then
  echo 'version 0.2.6'
  exit
fi

#Sofia's help module
if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
  help
fi

if [ "$1" == "slim" ]; then
  create_slim $2
fi

if [ "$1" == "create" ]; then
  create_default $2
fi

if [ "$1" == "run" ]; then
  echo "run!"
fi


